server:
  port: 8081

spring:
  rabbitmq:
    host: ${RABBITMQ_URL:localhost}
    username: scadareforged
    password: scadareforged
    listener:
      simple:
        acknowledge-mode: manual

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/docs