server:
  port: 8080

influxdb:
  url: ${INFLUXDB_URL:http://localhost:8086}
  token: ${INFLUXDB_TOKEN:_3GcH4taG4cVjFciP7CsQC8eMd-MHQ2r6JHBaM1zLljlk2tKJxvl7Er-0zLwBL6cAluyb4gxzFCsVwtAfCN1kQ==}
  organization: scadareforged
  bucket: datasources

jwt-security:
  secret: PseudoSecret-Pseudosecret-Please-Use-Ur-Own-Key-PseudoSecret-Pseudosecret
  expiration-time: 365

security:
  password-encoder:
    security-strength: 12

auth0:
  audience: scada

scada:
  service:
    virtual:
      url: ${DS_VIRTUAL_URL:localhost:8081}

logging:
  level:
   org:
    springframework:
      aop: DEBUG
      security:
        acls:
          AclPermissionEvaluator: DEBUG

spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  jpa:
    hibernate:
      ddl-auto: update
#    defer-datasource-initialization: true
  datasource:
    username: admin
    password: pass1234
    platform: h2
    url: jdbc:h2:mem:db
    #    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #    url: jdbc:h2:file:~/scada
    driverClassName: org.h2.Driver
    initialization-mode: always

  rabbitmq:
    host: ${RABBITMQ_URL:localhost}
    username: scadareforged
    password: scadareforged
    listener:
      simple:
        acknowledge-mode: manual

  security:
    user:
      name: administrator
      password: password
    filter:
      order: 10

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/docs
