name: Release Scada-Reforged
on:
  push:
    tags:
      - 'v*'

jobs:

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set version tag
        id: variables
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'
      - name: Build Core
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: :srf-core:bootJar
      - name: Build Virtual Service
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: :srf-ds-virtual:bootJar
      - name: Upload srf-core.jar
        uses: actions/upload-artifact@v3
        with:
          name: srf-core-${{ steps.variables.outputs.tag }}.jar
          path: ./srf-core/build/libs/srf-core-*.jar
      - name: Upload srf-ds-virtual.jar
        uses: actions/upload-artifact@v3
        with:
          name: srf-ds-virtual-${{ steps.variables.outputs.tag }}.jar
          path: ./srf-ds-virtual/build/libs/srf-ds-virtual-*.jar
